# src/newVisual.py

import json
import sys
import os
import pygame # type: ignore # Adding type ignore for Pygame if needed

# --- 添加项目根目录到 Python 路径 ---
# Ensure packages like src, levels, elements can be found
script_dir = os.path.dirname(__file__)
project_root = os.path.abspath(os.path.join(script_dir, '..'))
sys.path.append(project_root)
# ------------------------------------

# --- 导入你的 Game 类 ---
try:
    # Assuming Game class is in src/controller/game.py based on previous context
    from src.controller.game import Game
    # Import level data if you want to specify a different level later
    # from levels.level import level_1, level_2 # etc.
except ImportError as e:
    print(f"Error importing the Game class: {e}")
    print("Ensure 'Game' is in 'src/controller/game.py' or update the import path.")
    print(f"Project root added to path: {project_root}")
    sys.exit(1)
# ---------------------

def load_actions_from_json(json_filepath):
    """
    从指定的 JSON 文件加载记录的动作序列。

    Args:
        json_filepath (str): 包含 recorded_actions 的 JSON 文件路径。

    Returns:
        list: 动作序列 (e.g., ['U', 'R', 'R', 'D', ...])。
        int/str: 原始模拟的最终得分 (如果可用, 否则 'N/A')。
        int/str: 原始模拟的总步数 (如果可用, 否则 'N/A')。
        None: 如果文件读取或解析失败，或缺少 'recorded_actions' 键。
    """
    try:
        with open(json_filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        actions = data.get("recorded_actions")
        # Get score/steps from the file generated by SaveDirections.py
        score = data.get("simulation_final_score", "N/A")
        steps = data.get("simulation_total_steps", "N/A")

        if actions is None:
            print(f"Error: Key 'recorded_actions' not found in {json_filepath}")
            return None, None, None
        if not isinstance(actions, list):
             print(f"Error: 'recorded_actions' in {json_filepath} is not a list.")
             return None, None, None

        print(f"Successfully loaded {len(actions)} actions from {json_filepath}")
        print(f"  Original Simulation Score: {score}, Steps: {steps}")
        return actions, score, steps

    except FileNotFoundError:
        print(f"Error: JSON file not found at {json_filepath}")
        return None, None, None
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from {json_filepath}")
        return None, None, None
    except Exception as e:
        print(f"An unexpected error occurred loading actions: {e}")
        return None, None, None


def replay_game_with_actions(actions, fps=30):
    """
    使用加载的动作序列在可视化模式下重玩游戏。

    Args:
        actions (list): 要执行的动作序列。
        fps (int): 重放的帧率。
    """
    if not actions:
        print("No actions to replay.")
        return

    print(f"Initializing Pygame for visual replay at {fps} FPS...")

    # Note: Pygame display/font init is handled within Game.__init__ when headless=False
    # pygame.init() # Not strictly necessary here as Game.__init__ calls parts of it

    try:
        # Instantiate Game (headless=False by default)
        # This will initialize pygame display, load config etc.
        game = Game()

        # Load the level layout (dots, walls, etc.)
        # Your Game class doesn't automatically load level in __init__, so call it here.
        game.loadLevel() # Uses default level_1 from your Game class

    except Exception as e:
        print(f"Error initializing the Game class or loading level: {e}")
        # Attempt to quit pygame if it was partially initialized
        if pygame.get_init():
             pygame.quit()
        return

    # Use the clock object created by the Game instance if available and not headless
    clock = game.clock if game.clock else pygame.time.Clock()
    action_index = 0

    print("Starting replay...")

    # --- REPLAY LOOP ---
    # Loop while the game logic says it's running AND we still have actions
    while game.isRunning and action_index < len(actions):
        # Handle window events (like closing the window)
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                game.isRunning = False # Use game's flag to signal exit

        if not game.isRunning:
            break

        current_action = actions[action_index]

        if hasattr(game, 'player') and game.player:
             game.player.setDirection(current_action)
        else:
             print("Error: Game object does not have a player attribute properly initialized.")
             game.isRunning = False # Stop the replay
             break

        game.update()

        if game.screen:
             game.render()
        else:
             print("Error: Game screen not available for rendering.")
             game.isRunning = False
             break

        action_index += 1
        clock.tick(fps)
    print("-" * 20)

    final_message = ""
    if not game.isRunning and action_index < len(actions):
        final_message = "Replay interrupted (Window closed or game ended internally)."
    elif action_index == len(actions):
        final_message = "Reached the end of the recorded action sequence."

        if game.isRunning:
             final_message += " (Game may not have finished based on actions)."
    else:
         final_message = "Replay loop ended unexpectedly."

    print(final_message)

    if game.screen:
        print("Displaying final frame for 2 seconds...")
        end_time = pygame.time.get_ticks() + 2000
        while pygame.time.get_ticks() < end_time:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    end_time = pygame.time.get_ticks()
            clock.tick(fps)

    print(f"Replay processed {action_index} actions.")
    # Access score directly from the game instance
    print(f"Final Score reported by game instance: {game.score}")

    pygame.quit()
    print("Pygame closed.")


if __name__ == "__main__":
    actions_file = os.path.join(script_dir, "recorded_actions_ai_1.json") # Example ID 1
    # actions_file = "path/to/your/recorded_actions_ai_XYZ.json" # Alternative path

    replay_fps = 60

    print("--- Starting Visual Replay from Recorded Actions ---")
    print(f"Loading actions from: {actions_file}")

    recorded_actions, sim_score, sim_steps = load_actions_from_json(actions_file)

    if recorded_actions:
        replay_game_with_actions(recorded_actions, fps=replay_fps)
    else:
        print("Could not load actions. Exiting.")

    print("--- Visual Replay Script Finished ---")